//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.16 at 04:38:17 PM CEST
//

package com.ontimize.jee.server.dao.jdbc.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AmbiguousColumnType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AmbiguousColumnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="databaseName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AmbiguousColumnType")
public class AmbiguousColumnType {

    @XmlAttribute(name = "name", required = true)
    protected String name;

    @XmlAttribute(name = "prefix")
    protected String prefix;

    @XmlAttribute(name = "databaseName")
    protected String databaseName;

    /**
     * Gets the value of the name property.
     * @return possible object is {@link String }
     *
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the prefix property.
     * @return possible object is {@link String }
     *
     */
    public String getPrefix() {
        return this.prefix;
    }

    /**
     * Sets the value of the prefix property.
     * @param value allowed object is {@link String }
     *
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the databaseName property.
     * @return possible object is {@link String }
     *
     */
    public String getDatabaseName() {
        return this.databaseName;
    }

    /**
     * Sets the value of the databaseName property.
     * @param value allowed object is {@link String }
     *
     */
    public void setDatabaseName(String value) {
        this.databaseName = value;
    }

}
