//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.16 at 04:38:17 PM CEST
//

package com.ontimize.jee.server.dao.jdbc.setup;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for FunctionColumnsType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FunctionColumnsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FunctionColumn" type="{http://www.ontimize.com/schema/jdbc}FunctionColumnType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FunctionColumnsType", propOrder = { "functionColumn" })
public class FunctionColumnsType {

    @XmlElement(name = "FunctionColumn", required = true)
    protected List<FunctionColumnType> functionColumn;

    /**
     * Gets the value of the functionColumn property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is why
     * there is not a <CODE>set</CODE> method for the functionColumn property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getFunctionColumn().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link FunctionColumnType }
     *
     *
     */
    public List<FunctionColumnType> getFunctionColumn() {
        if (this.functionColumn == null) {
            this.functionColumn = new ArrayList<>();
        }
        return this.functionColumn;
    }

}
