//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.16 at 04:38:17 PM CEST
//

package com.ontimize.jee.server.dao.jdbc.setup;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.ontimize.jee.server.dao.jdbc.setup package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _JdbcEntitySetup_QNAME = new QName("http://www.ontimize.com/schema/jdbc",
            "JdbcEntitySetup");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for
     * package: com.ontimize.jee.server.dao.jdbc.setup
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JdbcEntitySetupType }
     *
     */
    public JdbcEntitySetupType createJdbcEntitySetupType() {
        return new JdbcEntitySetupType();
    }

    /**
     * Create an instance of {@link FunctionColumnType }
     *
     */
    public FunctionColumnType createFunctionColumnType() {
        return new FunctionColumnType();
    }

    /**
     * Create an instance of {@link QueryType }
     *
     */
    public QueryType createQueryType() {
        return new QueryType();
    }

    /**
     * Create an instance of {@link FunctionColumnsType }
     *
     */
    public FunctionColumnsType createFunctionColumnsType() {
        return new FunctionColumnsType();
    }

    /**
     * Create an instance of {@link AmbiguousColumnsType }
     *
     */
    public AmbiguousColumnsType createAmbiguousColumnsType() {
        return new AmbiguousColumnsType();
    }

    /**
     * Create an instance of {@link AmbiguousColumnType }
     *
     */
    public AmbiguousColumnType createAmbiguousColumnType() {
        return new AmbiguousColumnType();
    }

    /**
     * Create an instance of {@link QueriesType }
     *
     */
    public QueriesType createQueriesType() {
        return new QueriesType();
    }

    /**
     * Create an instance of {@link SentenceType }
     *
     */
    public SentenceType createSentenceType() {
        return new SentenceType();
    }

    /**
     * Create an instance of {@link ColumnGroupType }
     *
     */
    public ColumnGroupType createColumnGroupType() {
        return new ColumnGroupType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JdbcEntitySetupType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.ontimize.com/schema/jdbc", name = "JdbcEntitySetup")
    public JAXBElement<JdbcEntitySetupType> createJdbcEntitySetup(JdbcEntitySetupType value) {
        return new JAXBElement<>(ObjectFactory._JdbcEntitySetup_QNAME, JdbcEntitySetupType.class, null, value);
    }

}
