//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.16 at 04:38:17 PM CEST
//

package com.ontimize.jee.server.dao.cql.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * Elemento raiz para la configuracion de la entidad.
 *
 *
 * <p>
 * Java class for CassandraEntitySetupType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CassandraEntitySetupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeleteKeys" type="{http://www.ontimize.com/schema/jdbc}ColumnGroupType" minOccurs="0"/>
 *         &lt;element name="UpdateKeys" type="{http://www.ontimize.com/schema/jdbc}ColumnGroupType" minOccurs="0"/>
 *         &lt;element name="Queries" type="{http://www.ontimize.com/schema/jdbc}QueriesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="keyspace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="table" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CassandraEntitySetupType", propOrder = { "deleteKeys", "updateKeys", "queries" })
public class CassandraEntitySetupType {

	@XmlElement(name = "DeleteKeys")
	protected ColumnGroupType	deleteKeys;
	@XmlElement(name = "UpdateKeys")
	protected ColumnGroupType	updateKeys;
	@XmlElement(name = "Queries")
	protected QueriesType		queries;
	@XmlAttribute(name = "table")
	protected String			table;
	@XmlAttribute(name = "keyspace")
	protected String			keyspace;

	/**
	 * Gets the value of the deleteKeys property.
	 *
	 * @return possible object is {@link ColumnGroupType }
	 *
	 */
	public ColumnGroupType getDeleteKeys() {
		return this.deleteKeys;
	}

	/**
	 * Sets the value of the deleteKeys property.
	 *
	 * @param value
	 *            allowed object is {@link ColumnGroupType }
	 *
	 */
	public void setDeleteKeys(ColumnGroupType value) {
		this.deleteKeys = value;
	}

	/**
	 * Gets the value of the updateKeys property.
	 *
	 * @return possible object is {@link ColumnGroupType }
	 *
	 */
	public ColumnGroupType getUpdateKeys() {
		return this.updateKeys;
	}

	/**
	 * Sets the value of the updateKeys property.
	 *
	 * @param value
	 *            allowed object is {@link ColumnGroupType }
	 *
	 */
	public void setUpdateKeys(ColumnGroupType value) {
		this.updateKeys = value;
	}

	/**
	 * Gets the value of the queries property.
	 *
	 * @return possible object is {@link QueriesType }
	 *
	 */
	public QueriesType getQueries() {
		return this.queries;
	}

	/**
	 * Sets the value of the queries property.
	 *
	 * @param value
	 *            allowed object is {@link QueriesType }
	 *
	 */
	public void setQueries(QueriesType value) {
		this.queries = value;
	}

	/**
	 * Gets the value of the table property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTable() {
		return this.table;
	}

	/**
	 * Sets the value of the table property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setTable(String value) {
		this.table = value;
	}

	/**
	 * Gets the value of the keyspace property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getKeyspace() {
		return this.keyspace;
	}

	/**
	 * Sets the value of the keyspace property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setKeyspace(String keyspace) {
		this.keyspace = keyspace;
	}

}
