//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.21 at 11:50:12 AM CEST
//

package com.ontimize.jee.server.dao.jpa.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ColumnMapping complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ColumnMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dbColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dbColumnType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="beanAttribute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="beanAttributeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="beanAttributeGetterMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="beanAttributeSetterMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColumnMapping")
public class ColumnMapping {

    @XmlAttribute(name = "dbColumn", required = true)
    protected String dbColumn;

    @XmlAttribute(name = "dbColumnType", required = true)
    protected String dbColumnType;

    @XmlAttribute(name = "beanAttribute", required = true)
    protected String beanAttribute;

    @XmlAttribute(name = "beanAttributeType", required = true)
    protected String beanAttributeType;

    @XmlAttribute(name = "beanAttributeGetterMethod")
    protected String beanAttributeGetterMethod;

    @XmlAttribute(name = "beanAttributeSetterMethod")
    protected String beanAttributeSetterMethod;

    /**
     * Gets the value of the dbColumn property.
     * @return possible object is {@link String }
     *
     */
    public String getDbColumn() {
        return this.dbColumn;
    }

    /**
     * Sets the value of the dbColumn property.
     * @param value allowed object is {@link String }
     *
     */
    public void setDbColumn(String value) {
        this.dbColumn = value;
    }

    /**
     * Gets the value of the dbColumnType property.
     * @return possible object is {@link String }
     *
     */
    public String getDbColumnType() {
        return this.dbColumnType;
    }

    /**
     * Sets the value of the dbColumnType property.
     * @param value allowed object is {@link String }
     *
     */
    public void setDbColumnType(String value) {
        this.dbColumnType = value;
    }

    /**
     * Gets the value of the beanAttribute property.
     * @return possible object is {@link String }
     *
     */
    public String getBeanAttribute() {
        return this.beanAttribute;
    }

    /**
     * Sets the value of the beanAttribute property.
     * @param value allowed object is {@link String }
     *
     */
    public void setBeanAttribute(String value) {
        this.beanAttribute = value;
    }

    /**
     * Gets the value of the beanAttributeType property.
     * @return possible object is {@link String }
     *
     */
    public String getBeanAttributeType() {
        return this.beanAttributeType;
    }

    /**
     * Sets the value of the beanAttributeType property.
     * @param value allowed object is {@link String }
     *
     */
    public void setBeanAttributeType(String value) {
        this.beanAttributeType = value;
    }

    /**
     * Gets the value of the beanAttributeGetterMethod property.
     * @return possible object is {@link String }
     *
     */
    public String getBeanAttributeGetterMethod() {
        return this.beanAttributeGetterMethod;
    }

    /**
     * Sets the value of the beanAttributeGetterMethod property.
     * @param value allowed object is {@link String }
     *
     */
    public void setBeanAttributeGetterMethod(String value) {
        this.beanAttributeGetterMethod = value;
    }

    /**
     * Gets the value of the beanAttributeSetterMethod property.
     * @return possible object is {@link String }
     *
     */
    public String getBeanAttributeSetterMethod() {
        return this.beanAttributeSetterMethod;
    }

    /**
     * Sets the value of the beanAttributeSetterMethod property.
     * @param value allowed object is {@link String }
     *
     */
    public void setBeanAttributeSetterMethod(String value) {
        this.beanAttributeSetterMethod = value;
    }

}
