//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.21 at 11:50:12 AM CEST
//

package com.ontimize.jee.server.dao.jpa.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * Elemento raiz para la configuracion de la entidad.
 *
 *
 * <p>
 * Java class for JpaEntitySetupType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="JpaEntitySetupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Queries" type="{http://jpaentity.server.jee.imatia.com/setup}QueriesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="bean" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entitymanager" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JpaEntitySetupType", propOrder = { "queries" })
public class JpaEntitySetupType {

    @XmlElement(name = "Queries")
    protected QueriesType queries;

    @XmlAttribute(name = "bean")
    protected String bean;

    @XmlAttribute(name = "entitymanager")
    protected String entitymanager;

    /**
     * Gets the value of the queries property.
     * @return possible object is {@link QueriesType }
     *
     */
    public QueriesType getQueries() {
        return this.queries;
    }

    /**
     * Sets the value of the queries property.
     * @param value allowed object is {@link QueriesType }
     *
     */
    public void setQueries(QueriesType value) {
        this.queries = value;
    }

    /**
     * Gets the value of the bean property.
     * @return possible object is {@link String }
     *
     */
    public String getBean() {
        return this.bean;
    }

    /**
     * Sets the value of the bean property.
     * @param value allowed object is {@link String }
     *
     */
    public void setBean(String value) {
        this.bean = value;
    }

    /**
     * Gets the value of the entitymanager property.
     * @return possible object is {@link String }
     *
     */
    public String getEntitymanager() {
        return this.entitymanager;
    }

    /**
     * Sets the value of the entitymanager property.
     * @param value allowed object is {@link String }
     *
     */
    public void setEntitymanager(String value) {
        this.entitymanager = value;
    }

}
