//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.21 at 11:50:12 AM CEST
//

package com.ontimize.jee.server.dao.jpa.setup;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.ontimize.jee.server.dao.jpa.setup package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _JpaEntitySetup_QNAME = new QName("http://jpaentity.server.jee.imatia.com/setup",
            "JpaEntitySetup");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for
     * package: com.ontimize.jee.server.dao.jpa.setup
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JpaEntitySetupType }
     *
     */
    public JpaEntitySetupType createJpaEntitySetupType() {
        return new JpaEntitySetupType();
    }

    /**
     * Create an instance of {@link FunctionColumnType }
     *
     */
    public FunctionColumnType createFunctionColumnType() {
        return new FunctionColumnType();
    }

    /**
     * Create an instance of {@link QueryType }
     *
     */
    public QueryType createQueryType() {
        return new QueryType();
    }

    /**
     * Create an instance of {@link FunctionColumnsType }
     *
     */
    public FunctionColumnsType createFunctionColumnsType() {
        return new FunctionColumnsType();
    }

    /**
     * Create an instance of {@link AmbiguousColumnsType }
     *
     */
    public AmbiguousColumnsType createAmbiguousColumnsType() {
        return new AmbiguousColumnsType();
    }

    /**
     * Create an instance of {@link AmbiguousColumnType }
     *
     */
    public AmbiguousColumnType createAmbiguousColumnType() {
        return new AmbiguousColumnType();
    }

    /**
     * Create an instance of {@link ReturnType }
     *
     */
    public ReturnType createReturnType() {
        return new ReturnType();
    }

    /**
     * Create an instance of {@link QueriesType }
     *
     */
    public QueriesType createQueriesType() {
        return new QueriesType();
    }

    /**
     * Create an instance of {@link ColumnMapping }
     *
     */
    public ColumnMapping createColumnMapping() {
        return new ColumnMapping();
    }

    /**
     * Create an instance of {@link SentenceType }
     *
     */
    public SentenceType createSentenceType() {
        return new SentenceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JpaEntitySetupType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://jpaentity.server.jee.imatia.com/setup", name = "JpaEntitySetup")
    public JAXBElement<JpaEntitySetupType> createJpaEntitySetup(JpaEntitySetupType value) {
        return new JAXBElement<>(ObjectFactory._JpaEntitySetup_QNAME, JpaEntitySetupType.class, null, value);
    }

}
