//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.21 at 11:50:12 AM CEST 
//


package com.ontimize.jee.server.dao.jpa.setup;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReturnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReturnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="column-mapping" type="{http://jpaentity.server.jee.imatia.com/setup}ColumnMapping" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="returnType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="returnDbColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="returnDbType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReturnType", propOrder = {
    "columnMapping"
})
public class ReturnType {

    @XmlElement(name = "column-mapping")
    protected List<ColumnMapping> columnMapping;
    @XmlAttribute(name = "returnType")
    protected String returnType;
    @XmlAttribute(name = "returnDbColumn")
    protected String returnDbColumn;
    @XmlAttribute(name = "returnDbType")
    protected String returnDbType;

    /**
     * Gets the value of the columnMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columnMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumnMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColumnMapping }
     * 
     * 
     */
    public List<ColumnMapping> getColumnMapping() {
        if (columnMapping == null) {
            columnMapping = new ArrayList<ColumnMapping>();
        }
        return this.columnMapping;
    }

    /**
     * Gets the value of the returnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnType() {
        return returnType;
    }

    /**
     * Sets the value of the returnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnType(String value) {
        this.returnType = value;
    }

    /**
     * Gets the value of the returnDbColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnDbColumn() {
        return returnDbColumn;
    }

    /**
     * Sets the value of the returnDbColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnDbColumn(String value) {
        this.returnDbColumn = value;
    }

    /**
     * Gets the value of the returnDbType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnDbType() {
        return returnDbType;
    }

    /**
     * Sets the value of the returnDbType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnDbType(String value) {
        this.returnDbType = value;
    }

}
