package com.ontimize.jee.server.dao.jdbc;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * @author Enrique Alvarez Pereira <enrique.alvarez@imatia.com>
 */
public class InMemoryDatabaseStructure {

    public void databaseStructureCreation(Statement dbStatement, Connection dbConnection) {
        // Data generated with https://www.mockaroo.com/
        try {
            dbStatement.execute("CREATE TABLE employees (employeeid INT NOT NULL, name VARCHAR(50) NOT NULL,"
                    + "email VARCHAR(50) NOT NULL,"
                    + "uniqueid INT GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL, PRIMARY KEY (employeeid))");

            dbStatement.execute("CREATE TABLE accounts (accountid INT NOT NULL, name VARCHAR(50) NOT NULL,"
                    + "balance DOUBLE NOT NULL, PRIMARY KEY (accountid))");

            dbStatement.execute("CREATE TABLE employeeaccounts (eaccountsid INT NOT NULL, employeeid INT NOT NULL,"
                    + "accountid INT, name VARCHAR(50), PRIMARY KEY (eaccountsid), "
                    + "CONSTRAINT FK_EMPLOYEE FOREIGN KEY(employeeid) REFERENCES employees(employeeid),"
                    + "CONSTRAINT FK_ACCOUNT FOREIGN KEY(accountid) REFERENCES accounts(accountid))");
            dbConnection.commit();

            dbStatement.executeUpdate("INSERT INTO employees VALUES (1001, 'Jeramie', 'jpenticost0@statcounter.com', 0)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1002, 'Paddy', 'poconnell1@flickr.com', 1)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1003, 'Valentin', 'vdongles2@opensource.org', 2)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1004, 'Byrle', 'bserjeant3@digg.com', 3)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1005, 'Karel', 'krickard4@forbes.com', 4)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1006, 'Dionis', 'dallard5@simplemachines.org', 5)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1007, 'Terrell', 'tpoynter6@ebay.co.uk', 6)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1008, 'Simon', 'shabbin7@gov.uk', 7)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1009, 'Anitra', 'abrocking8@cdbaby.com', 8)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1010, 'Marta', 'mpendrid9@webnode.com', 9)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1011, 'Ellynn', 'emorcoma@icq.com', 10)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1012, 'Brana', 'bgurleyb@telegraph.co.uk', 11)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1013, 'Vivian', 'vjaulmec@dmoz.org', 12)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1014, 'Arlyne', 'agartind@unicef.org', 13)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1015, 'Vania', 'vbournee@hao123.com', 14)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1016, 'Leoine', 'lchasteyf@i2i.jp', 15)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1017, 'Kai', 'kcalking@va.gov', 16)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1018, 'Hillyer', 'hgeorgeoth@house.gov', 17)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1019, 'Josey', 'jsevitti@salon.com', 18)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1020, 'Merrielle', 'mchisolmj@nyu.edu', 19)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1021, 'Lilias', 'leynaudk@un.org', 20)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1022, 'Verne', 'vphillpsl@godaddy.com', 21)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1023, 'Matthias', 'mfryem@altervista.org', 22)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1024, 'Felicio', 'fquantrilln@barnesandnoble.com', 23)");
            dbStatement.executeUpdate("INSERT INTO employees VALUES (1025, 'Kevan', 'kelcoato@etsy.com', 24)");

            dbStatement.executeUpdate("INSERT INTO accounts VALUES (101,'Lehner Group', 1890.23)");
            dbStatement.executeUpdate("INSERT INTO accounts VALUES (102,'Balistreri and Wiegand', 567889.34)");
            dbStatement.executeUpdate("INSERT INTO accounts VALUES (103,'DuBuque Group', 4532.10)");
            dbStatement.executeUpdate("INSERT INTO accounts VALUES (104,'Price and Sons', 4456645.77)");
            dbStatement.executeUpdate("INSERT INTO accounts VALUES (105,'Mayer Inc', 18765.56)");

            dbStatement.executeUpdate("INSERT INTO employeeaccounts VALUES (1, 1001, 101, 'T1')");
            dbStatement.executeUpdate("INSERT INTO employeeaccounts VALUES (2, 1002, 102, 'T2')");
            dbStatement.executeUpdate("INSERT INTO employeeaccounts VALUES (3, 1003, 103, 'T3')");
            dbStatement.executeUpdate("INSERT INTO employeeaccounts VALUES (4, 1004, 104, 'T4')");
            dbStatement.executeUpdate("INSERT INTO employeeaccounts VALUES (5, 1005, 105, 'T5')");
            dbStatement.executeUpdate("INSERT INTO employeeaccounts VALUES (6, 1006, null, 'T6')");

            dbConnection.commit();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void databaseDelete(Statement dbStatement, Connection dbConnection) {
        try {
            dbStatement.executeUpdate("DROP TABLE employeeaccounts");
            dbStatement.executeUpdate("DROP TABLE employees");
            dbStatement.executeUpdate("DROP TABLE accounts");
            dbConnection.commit();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

}
