name: Generate a snapshot in MVNCentral
on: 
  push:
    branches:    
      - 'develop'
jobs:
  Generate-a-snapshot-in-MVNCentral:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repository code
        uses: actions/checkout@v4
      - name: Setup Java JDK and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE       
      - name: Publish to Apache Maven Central
        run: mvn -U clean deploy -Pgenerate-version
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}